[project]
name = "pipeline-services"
version = "0.1.0"
description = "Pipeline Services – Python port"
authors = [{name="Nektarios Kalogridis"}]
readme = "README.md"
requires-python = ">=3.9"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
